# Generated by Django 5.0.1 on 2024-01-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kantors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kantor',
            old_name='description',
            new_name='lokasi',
        ),
    ]
