# Generated by Django 5.0.1 on 2024-01-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kantors', '0004_alter_kantor_departemen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kantor',
            name='departemen',
        ),
    ]
