# Generated by Django 5.0.1 on 2024-01-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kantors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratting', models.IntegerField()),
                ('body', models.TextField()),
                ('kantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kantor', to='kantors.kantor')),
            ],
        ),
    ]
