# Generated by Django 5.0.1 on 2024-01-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kantors', '0005_remove_kantor_departemen'),
        ('karyawans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ratting',
        ),
        migrations.AddField(
            model_name='review',
            name='jabatan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='nama',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='kantor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='kantor', to='kantors.kantor'),
        ),
    ]
