# Generated by Django 5.0.1 on 2024-01-16 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kantors', '0006_kantor_departemen'),
        ('karyawans', '0002_remove_review_body_remove_review_ratting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='kantor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='kantors', to='kantors.kantor'),
        ),
    ]
