# Generated by Django 5.0.1 on 2024-01-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawans', '0004_alter_review_kantor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='kantor',
        ),
    ]
